name: Auto-documentation Generation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pdoc3
      run: |
        python -m pip install --upgrade pip
        pip install pdoc3

    - name: Remove existing documentation files
      run: rm -rf docs/*

    - name: Retrieve package name
      id: get_package_name
      run: |
       name=$(python setup.py --name)

    - name: Generate documentation
      run: |
        pdoc --html --output-dir docs ${{ steps.get_package_name.outputs.name }}

    - name: Copy documentation files
      run: |
        cp -r docs/${{ steps.get_package_name.outputs.name }}/* docs/

    - name: Commit documentation changes
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_EMAIL: action@github.com
      run: |
        git config user.email "${GITHUB_EMAIL}"
        git config user.name "${GITHUB_ACTOR}"
        git add docs/
        git commit -m "Auto-generated documentation"
        git push
